---
title: "People"
link-external-icon: false
---

<script src="https://kit.fontawesome.com/52811a1d50.js" crossorigin="anonymous"></script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, file = here::here("snippets", "team_members.R")}
```

Team members are staff, students and long-term visitors (3 months or more) of the consortia.

## Current team members

```{r, results='asis'}
field <- function(e, name) {
  value <- e[[name]]

  if (is.null(value) || length(value) == 0 || all(is.na(value))) {
    return("")
  }

  paste(as.character(value), collapse = " ")
}

role <- function(e) {
  position <- e[["position"]]

  if (is.null(position) || length(position) == 0) {
    return("")
  }

  if (is.character(position)) {
    return(paste(position, collapse = ", "))
  }

  purrr::map_chr(position, \(p) {
    if (is.list(p)) field(p, "type") else as.character(p)
  }) |>
    purrr::discard(\(value) is.na(value) || value == "") |>
    paste(collapse = ", ")
}

expanded <- purrr::map_chr(current_team, function(e) {
  knitr::knit_expand(
    "_team_member.Rmd", 
    name = field(e, "name"),
    affiliation = field(e, "affiliation"),
    role = role(e),
    email = field(e, "email"),
    image = field(e, "image"),
    webpage = field(e, "webpage"),
    github = field(e, "github"),
    twitter = field(e, "twitter"),
    bluesky = field(e, "bluesky"),
    orcid = field(e, "orcid"),
    description = field(e, "description")
  )
})

expanded_text <- paste(expanded, collapse = "\n\n")

child_output <- knitr::knit_child(
  text = expanded_text,
  quiet = TRUE
)

cat(child_output, sep = "\n")
```

## Former team members

```{r, results='asis'}
former_team <- team[setdiff(names(team), names(current_team))] |>
  purrr::map_chr(function(e) {
    if (is.null(e[["webpage"]]) || e[["webpage"]] == "") {
      e[["name"]]
    } else {
      glue::glue('[{e[["name"]]}]({e[["webpage"]]})')
    }
  }) |>
  cat(sep = " · ")
```
